### PR TITLE
Fix the crash caused by newly started process while jtop is running

### LINKED ISSUE #499: Crash on start or during runtime
## To Reproduce

Jetson Xavier NX fully updated

## Expected behavior

Crashes on startup or while open. Random

## Additional context

Here is the crash log:

```
Traceback (most recent call last):
  File "/usr/local/bin/jtop", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/jtop/__main__.py", line 160, in main
    curses.wrapper(JTOPGUI, jetson, pages, init_page=args.page,
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/jtop/gui/jtopgui.py", line 100, in __init__
    self.run(loop, seconds)
  File "/usr/local/lib/python3.8/dist-packages/jtop/gui/jtopgui.py", line 129, in run
    self.draw()
  File "/usr/local/lib/python3.8/dist-packages/jtop/gui/jtopgui.py", line 143, in draw
    page.draw(self.key, self.mouse)
  File "/usr/local/lib/python3.8/dist-packages/jtop/gui/pall.py", line 147, in draw
    line_counter += self.process_table.draw(line_counter, 0, width, height_free_area, key, mouse)
AttributeError: 'ALL' object has no attribute 'process_table'
```

### Board

 - 699-level Part Number: 699-13668-0000-200 G.0
 - P-Number: p3668-0000
 - Module: NVIDIA Jetson Xavier NX (Developer kit)
 - SoC: tegra194
 - CUDA Arch BIN: 7.2
 - Codename: Jakku
Platform:
 - Machine: aarch64
 - System: Linux
 - Distribution: Ubuntu 20.04 focal
 - Release: 5.10.104_np_tegra
 - Python: 3.8.10
jtop:
 - Version: 4.2.6
 - Service: Active
Libraries:
 - CUDA: 11.4.315
 - cuDNN: 8.6.0.166
 - TensorRT: 8.5.2.2
 - VPI: 2.2.7
 - Vulkan: 1.3.204
 - OpenCV: 4.5.4 - with CUDA: NO
### Log from jtop.service

Attach here the output from: `journalctl -u jtop.service -n 100 --no-pager`

-- Logs begin at Tue 2023-11-21 22:10:22 CET, end at Sat 2024-03-09 20:55:58 CET. --
nov 21 22:10:42 NV-J-X-NX systemd[1]: Started jtop service.
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.service - jetson_stats 4.2.6 - server loaded
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.service - Running on Python: 3.8.10
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.hardware - Hardware detected aarch64
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.hardware - NVIDIA Jetson 699-level Part Number=699-13668-0000-200 G.0
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.hardware - NVIDIA Jetson Module=NVIDIA Jetson Xavier NX (Developer kit)
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.hardware - NVIDIA Jetson detected L4T=35.3.1
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.cpu - Found 6 CPU
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.gpu - GPU "gv11b" status in /sys/devices/platform/17000000.gv11b
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.gpu - GPU "gv11b" frq in /sys/devices/platform/17000000.gv11b/devfreq/17000000.gv11b
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.processes - Process service started
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.memory - Found EMC!
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.memory - Memory service started
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.engine - Special Engine group found: [dlaX]
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.engine - Special Engine group found: [pvaX]
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.engine - Engines found: [APE CVNAS DLA0 DLA1 NVDEC NVENC NVJPG PVA0 PVA1 SE VIC]
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.temperature - Found thermal "AUX" in thermal_zone2
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.temperature - Found thermal "CPU" in thermal_zone0
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.temperature - Found thermal "thermal" in thermal_zone5
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.temperature - Found thermal "AO" in thermal_zone3
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.temperature - Found thermal "GPU" in thermal_zone1
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [WARNING] jtop.core.temperature - Skipped PMIC
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.power - Alarms VDD_IN - {'crit_alarm': 0, 'max_alarm': 0}
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.power - Alarms VDD_CPU_GPU_CV - {'crit_alarm': 0, 'max_alarm': 0}
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.power - Alarms VDD_SOC - {'crit_alarm': 0, 'max_alarm': 0}
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [WARNING] jtop.core.power - Skipped "sum of shunt voltages" /sys/bus/i2c/devices/7-0040/hwmon/hwmon5/in7_label
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.power - Found I2C power monitor
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [WARNING] jtop.core.power - Skipped usb-charger type=USB in=usb-charger
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.fan - Fan pwmfan(1) found in /sys/class/hwmon/hwmon4
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.fan - RPM pwm_tach found in /sys/class/hwmon/hwmon2
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.fan - Found nvfancontrol.service
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.jetson_clocks - jetson_clocks found in /usr/bin/jetson_clocks
nov 21 22:10:43 NV-J-X-NX jtop[2075]: [INFO] jtop.core.nvpmodel - nvpmodel running in [8]MODE_20W_6CORE - Default: 5
nov 21 22:10:43 NV-J-X-NX jtop[2099]: [INFO] jtop.service - Initialization service
nov 21 22:10:45 NV-J-X-NX jtop[2099]: [INFO] jtop.service - service ready
mar 09 20:54:08 NV-J-X-NX jtop[2099]: [INFO] jtop.service - jtop timer thread started 1000ms
mar 09 20:54:13 NV-J-X-NX jtop[2099]: [INFO] jtop.service - jtop timer thread close

### Log from jetson-stats installation

Using pip 24.0 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
Requirement already satisfied: jetson-stats in /usr/local/lib/python3.8/dist-packages (4.2.6)
Requirement already satisfied: distro in /usr/lib/python3/dist-packages (from jetson-stats) (1.4.0)
Requirement already satisfied: smbus2 in /usr/local/lib/python3.8/dist-packages (from jetson-stats) (0.4.2)
DEPRECATION: dblatex 0.3.11py3 has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of dblatex or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

### RAW Data

File from `jtop --error-log` attached

--------------------- PLATFORM -------------------------
Machine: aarch64
System: Linux
Distribution: Ubuntu 20.04 focal
Release: 5.10.104_np_tegra
Python: 3.8.10
-------------------- JETSON RAW OUTPUT -----------------
------------------
Path: /etc/nv_tegra_release
# R35 (release), REVISION: 3.1, GCID: 32827747, BOARD: t186ref, EABI: aarch64, DATE: Sun Mar 19 15:19:21 UTC 2023
------------------
Path: /sys/firmware/devicetree/base/model
NVIDIA Jetson Xavier NX Developer Kit
------------------
Path: /proc/device-tree/nvidia,boardids
No such file or directory
------------------
Path: /proc/device-tree/compatible
nvidia,p3449-0000+p3668-0000^@nvidia,p3509-0000+p3668-0000^@nvidia,tegra194
------------------
Path: /proc/device-tree/nvidia,dtsfilename
/dvs/git/dirty/git-master_linux/kernel/kernel-5.10/arch/arm64/boot/dts/../../../../../../hardware/nvidia/platform/t19x/>------------------
Path: I2C-0-0x50
01 00 FC 00 54 0E 00 00 02 47 00 00 00 00 00 00    ..ü.T....G......
00 00 00 00 36 39 39 2D 31 33 36 36 38 2D 30 30    ....699-13668-00
30 30 2D 32 30 30 20 47 2E 30 00 00 00 00 00 00    00-200 G.0......
00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF    ..ÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF 2D 9D 05 2D B0 48 31 34 32 31 30 32    ÿÿÿÿ-..-°H142102
30 30 31 30 33 32 33 00 00 00 00 00 00 00 00 00    0010323.........
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
00 00 00 00 00 00 4E 56 43 42 1C 00 4D 31 00 00    ......NVCB..M1..
FF FF FF FF FF FF FF FF FF FF FF FF 2D 9D 05 2D    ÿÿÿÿÿÿÿÿÿÿÿÿ-..-
B0 48 00 00 00 00 00 00 00 00 00 00 00 00 00 00    °H..............
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4E    ...............N

------------------
Path: I2C-0
FAIL
------------------
Path: I2C-1
FAIL
------------------
Path: I2C-2
FAIL
------------------
Path: I2C-7
FAIL

-------------------- IGPU OUTPUT ---------------------
------------------
Path: /sys/class/devfreq/15a80000.nvenc1/device/of_node/name
nvenc1
------------------
Path: /sys/class/devfreq/15480000.nvdec/device/of_node/name
nvdec
------------------
Path: /sys/class/devfreq/154c0000.nvenc/device/of_node/name
nvenc
------------------
Path: /sys/class/devfreq/17000000.gv11b/device/of_node/name
gv11b
------------------
Path: /sys/class/devfreq/15140000.nvdec1/device/of_node/name
nvdec1
------------------
Path: /sys/class/devfreq/15340000.vic/device/of_node/name
vic

### PR DESCRIPTION
**Pull request by gztong**
Fixes #499

### CODE REVIEW

**Comment by rbonghi** [comment]
Hi @gztong 

Thank you very much for your PR! I really appreciate any type of support :-)

Can you help me understand your fix? I see that you canceled the if condition on the processes table.
Have you tried jtop when there are no GPU processes running?

**Comment by gztong** [comment]
Hi @rbonghi ,
Thanks for getting back to me!

The fix simply adds the ProcessTable even IF there is no GPU process at first during the ALL object __init__. 
So that while jtop is running, if a new GPU process starts, jtop can add it to the process table for drawing.

>Have you tried jtop when there are no GPU processes running?
Yes, I did. In this case, the process table is simply empty. I don't see any issues.

**Comment by rbonghi** [comment]
Thank you @gztong 
I also noticed a similar call in another part of the code.
Let me merge on develop branch

**Comment by rbonghi** [comment]
Fixed with the new release. Please update to **4.2.9**

```
sudo pip3 install -U jetson-stats
```

**Pull request merged**
